name: Casco
author: Sebastian Erives
version: '1.0.0'
main: org.deltacv.casco.Casco
api-version: '1.21'
softdepend: ['Multiverse-Core', 'WorldBorderApi']

commands:
  casco:
    description: "Casco plugin management"
    usage: "casco <join|config|arenas|tp|start|stop>"